# Should the death message be sent?
SEND_DEATH_MESSAGE: true

# What is the death message?
DEATH_MESSAGE: "&e{DIED} &chas been killed by &e{KILLER}&c!"

# Should the first join message be sent?
SEND_FIRST_JOIN: true

# What is the first join message?
FIRST_JOIN_MESSAGE: "&e{PLAYER} has joined the server for the first time! Welcome them!"

# Should the regular join message be sent?
SEND_JOIN: true

# What is the join message?
JOIN_MESSAGE: "&e{PLAYER} has joined the server!"

# Should the quit message be sent?
SEND_QUIT: true

# What is the quit message?
QUIT_MESSAGE: "&e{PLAYER} has left the server!"
