name: Messages
version: "2.0"
author: garsh1
main: com.garsh.messages.MessagesPlugin
description: Change the messages of Minecraft with this lightweight and simple plugin!

commands:
  messages:
    usage: /messages
    description: Reload the configuration file
